version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - pip3 install awscli aws-sam-cli --upgrade
      - pip install -r requirements.txt -t .
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build
      - sam package -t template.yml --s3-bucket $S3_BUCKET --output-template-file ./template-export.yml

artifacts:
  type: zip
  files:
    - template.yml
    - template-export.yml
