version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - pip3 install awscli aws-sam-cli --upgrade
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file ./serverless-output.yaml

artifacts:
  type: zip
  files:
    - template-export.yml
